# Housing Crisis in Canada

## Overview
This project aims to analyze the housing crisis in Canada, exploring various factors contributing to the crisis and potential solutions.

## Installation
To run this project, ensure you have Python installed on your system. You'll also need to install the following Python libraries:
- NumPy
- pandas

You can install these libraries via pip:

```bash
pip install numpy pandas
```

## Usage
To use this project, follow these steps:
1. Clone this repository to your local machine.
2. Install the required dependencies as mentioned in the Installation section.
3. Open the Jupyter Notebook (or Python script) containing the analysis.
4. Execute the code cells to perform the analysis and visualize the results.

## Data
This analysis utilizes two datasets downloaded from Government of Canada's open data portal, related to the housing crisis in Canada. Please download the following datasets and place them in the appropriate directory:
1. [immigrant-status-and-period-of-immigration-e](https://open.canada.ca/data/en/dataset/9adddd8a-e15b-497c-86af-641457a78bea/resource/255012de-7f8a-4f5e-b62a-bc438dc89543)
2. [18100205](https://open.canada.ca/data/en/dataset/324befd1-893b-42e6-bece-6d30af3dd9f1)

## Analysis
The analysis includes the following steps:
- Data preprocessing
- Exploratory data analysis
- Statistical analysis

## Results
The key findings from the analysis will be summarized here.

## Future Work
Potential future enhancements or additional analyses for this project may include:
- Incorporating more datasets for a comprehensive analysis
- Building predictive models to forecast housing trends
- Exploring policy recommendations to address the housing crisis

## Contributors
- Muhammad Hunain Muneer

## License
MIT License

## Contact
For questions, feedback, or contributions, please contact hunain.muneer1995@gmail.com

In [67]:
### Thought on just the immigration data. Housing data is not that complicated (just need to remove unncessary columns)

# NOTE : Adding two new columns "timeframe" $ "No. of Immigrants (relative to time period) which will show which timeframe of immigration ------> (before 1996) (1696 to 2005)  (2006 to 2011)

# Expected dataframe for immigration_data 
# Link to data : https://open.canada.ca/data/en/dataset/9adddd8a-e15b-497c-86af-641457a78bea/resource/255012de-7f8a-4f5e-b62a-bc438dc89543

# First 2 rows:
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#|||    Immigrant status and period of immigration   |          Total - Immigrant status and period of immigration | Non-immigrants | Immigrants | No. of Immigrants (relative to time period)  |     timeframe       |||
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 
#             Canada                                 |                         27259525 	                       |    20543700    |   6398855  |                  3837770                     |    before 1996      |||
 
#   	      Canada                                 |                         27259525                            |    20543700    |   6398855  |                  1620885                     |    1996 - 2005      |||

In [68]:
### Expected Housing Dataframe
# Link to data : https://open.canada.ca/data/en/dataset/324befd1-893b-42e6-bece-6d30af3dd9f1

# First 2 rows:
#---------------------------------------------------------------------------------------------------------------------
#||| REF_DATE | Date     | GEO    | DGUID             | New housing price indexes | UOM        | VALUE | STATUS    |||
#---------------------------------------------------------------------------------------------------------------------

# 1981-01-01  |  before  | Canada | 2016A000011124	  | Total (house and land)    | Index, 	   | 38.2  |  NaN      |||
#                 1996   |                                                        | 201612=100 |
 
# 1981-01-01  |  before	 | Canada | 2016A000011124    |     House only	          | Index,     |  36.1 |  NaN      |||
#                  1996  |                                                        | 201612=100 |

In [69]:
### Thought 1   (Only the immigrants data that is in 3 time frames (before 1996) (1196 to 2005)  (2006 to 2011)) Also Total, Non-immigrants and Immigrants that only contain the total number as of 2011

# Expected dataframe after merging the housing_data and immigration_data 

# First 2 rows:
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#||| REF_DATE | Date     | GEO    | DGUID             | New housing price indexes | UOM        | VALUE | STATUS | Total - Immigrant status and period of immigration | Non-immigrants | Immigrants | No. of Immigrants (relative to time period) |||
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# 1981-01-01  |  before  | Canada | 2016A000011124	  | Total (house and land)    | Index, 	   | 38.2  |  NaN   |                27259525	                         |    20543700    |   6398855  |                  3837770                    |||
#                 1996   |                                                        | 201612=100 |
 
# 1981-01-01  |  before	 | Canada | 2016A000011124    |     House only	          | Index,     |  36.1 |  NaN   |   	         27259525                            |     20543700   |   6398855  |                  3837770                    |||
#                  1996  |                                                        | 201612=100 |

In [70]:
### Thought 2  Only 1 column that will be based on the timeframe (Only the immigrants data that is in 3 time frames (before 1996) (1996 to 2005)  (2006 to 2011))

# Expected dataframe after merging the housing_data and immigration_data 

# First 2 rows:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------
#||| REF_DATE | Date     | GEO    | DGUID             | New housing price indexes | UOM        | VALUE | STATUS | No. of Immigrants (relative to time period) |||
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

# 1981-01-01  |  before  | Canada | 2016A000011124	  | Total (house and land)    | Index, 	   | 38.2  |  NaN   |                3837770                      |||
#                 1996   |                                                        | 201612=100 |
 
# 1981-01-01  |  before	 | Canada | 2016A000011124    |     House only	          | Index,     |  36.1 |  NaN   |                3837770                      |||
#                  1996  |                                                        | 201612=100 |

###  Loading the two datasets using the pandas data frames

In [71]:
# Loading the housing data

import pandas as pd
import os

# Construct the file path relative to the notebook's directory
file_path = os.path.abspath("../data/raw/housing-index/18100205.csv")

try:
    housing_data = pd.read_csv(file_path)
    # Proceed with further processing of the dataframe
except FileNotFoundError:
    print("Error: File not found. Please ensure the file path is correct.")

#checking the first few rows of the data
housing_data.head()

,REF_DATE,GEO,DGUID,New housing price indexes,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1981-01,Canada,2016A000011124,Total (house and land),"Index, 201612=100",347,units,0,v111955442,1.1,38.2,NaN,NaN,NaN,1
1,1981-01,Canada,2016A000011124,House only,"Index, 201612=100",347,units,0,v111955443,1.2,36.1,NaN,NaN,NaN,1
2,1981-01,Canada,2016A000011124,Land only,"Index, 201612=100",347,units,0,v111955444,1.3,40.6,E,NaN,NaN,1
3,1981-01,Atlantic Region,2016A00011,Total (house and land),"Index, 201612=100",347,units,0,v111955445,2.1,NaN,..,NaN,NaN,1
4,1981-01,Atlantic Region,2016A00011,House only,"Index, 201612=100",347,units,0,v111955446,2.2,NaN,..,NaN,NaN,1

In [72]:
# Loading the immigration data

file_path_immigration = os.path.abspath("../data/raw/immigrant.csv")

try:
    # Try reading the CSV files with different encodings until successful
    immigration_data = pd.read_csv(file_path_immigration, encoding='latin1')
    # Proceed with further processing of the dataframes
except FileNotFoundError:
    print("Error: File not found. Please ensure the file paths are correct.")
except UnicodeDecodeError:
    print("Error: Unable to decode the file. Please check the file's encoding.")

#checking the first few rows of the data
immigration_data.head()

,"Table Title: Immigrant Status and Period of Immigration (6) for the Population Aged 15 Years and Over, in Private Households of Canada, Provinces, Territories and 11 selected Census Metropolitan Areas (CMA) (25), 2011 National Household Survey, Statistics Canada",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Immigrant status and period of immigration,Canada,Newfoundland and Labrador,Prince Edward Island,Nova Scotia / Nouvelle-Écosse,New Brunswick / Nouveau-Brunswick,Quebec,Ontario,Manitoba,Saskatchewan,...,Halifax CMA,Québec City CMA,Montréal CMA,Ottawa - Gatineau CMA,Toronto CMA,Winnipeg CMA,Regina CMA,Calgary CMA,Edmonton CMA,Vancouver CMA
1,Total - Immigrant status and period of immigra...,27259525,431045,114195,768060,622440,6474590,10473665,946940,812505,...,325050,634200,3120060,1005005,4546140,590295,170070,976570,935285,1926230
2,Non-immigrants,20543700,421170,107085,717140,593840,5511745,6912395,774365,744685,...,292010,602990,2278110,773525,2047970,451125,149025,665410,698240,1009070
3,Immigrants,6398855,8315,6415,44660,25890,902990,3442895,165005,60500,...,28685,28605,789440,220640,2416425,133380,19055,290760,216460,870035
4,Before 1996,3837770,5415,3455,28690,16530,496790,2148600,90000,29120,...,16775,11985,439575,130700,1408665,74005,9415,145920,123735,486590

**-> housing_data is loaded in correct format but the immigration_data has to be changed to horizontal data from vertical**

**-> We want to have the areas/province/metropolitan areas in the same column and can have same data type for the columns in our dataset. Currently we have string and numerical data in the same column as show above**

In [73]:
# Converting data form horizontal view to vertical view so all the areas are in the same column
immigration_data = immigration_data.transpose()
immigration_data.head()

,0,1,2,3,4,5,6
"Table Title: Immigrant Status and Period of Immigration (6) for the Population Aged 15 Years and Over, in Private Households of Canada, Provinces, Territories and 11 selected Census Metropolitan Areas (CMA) (25), 2011 National Household Survey, Statistics Canada",Immigrant status and period of immigration,Total - Immigrant status and period of immigra...,Non-immigrants,Immigrants,Before 1996,1996 to 2005,2006 to 2011
Unnamed: 1,Canada,27259525,20543700,6398855,3837770,1620885,940195
Unnamed: 2,Newfoundland and Labrador,431045,421170,8315,5415,1215,1690
Unnamed: 3,Prince Edward Island,114195,107085,6415,3455,920,2035
Unnamed: 4,Nova Scotia / Nouvelle-Écosse,768060,717140,44660,28690,7485,8485

In [74]:
# The index is not correct so we will drop it from the dataset
# We will use reset_index() method to drop the index and we want to change the dataset itself and will set the inplace parameter to True

immigration_data.reset_index(drop= True, inplace= True)
immigration_data.head()

,0,1,2,3,4,5,6
0,Immigrant status and period of immigration,Total - Immigrant status and period of immigra...,Non-immigrants,Immigrants,Before 1996,1996 to 2005,2006 to 2011
1,Canada,27259525,20543700,6398855,3837770,1620885,940195
2,Newfoundland and Labrador,431045,421170,8315,5415,1215,1690
3,Prince Edward Island,114195,107085,6415,3455,920,2035
4,Nova Scotia / Nouvelle-Écosse,768060,717140,44660,28690,7485,8485

In [75]:
# The column in our dataset is wrong as we want the first row to be our columns
# Current columns

immigration_data.columns

RangeIndex(start=0, stop=7, step=1)

In [76]:
# Setting the frist row as the columns of the dataframe

immigration_data.columns = immigration_data.iloc[0]
immigration_data.head()

,Immigrant status and period of immigration,Total - Immigrant status and period of immigration,Non-immigrants,Immigrants,Before 1996,1996 to 2005,2006 to 2011
0,Immigrant status and period of immigration,Total - Immigrant status and period of immigra...,Non-immigrants,Immigrants,Before 1996,1996 to 2005,2006 to 2011
1,Canada,27259525,20543700,6398855,3837770,1620885,940195
2,Newfoundland and Labrador,431045,421170,8315,5415,1215,1690
3,Prince Edward Island,114195,107085,6415,3455,920,2035
4,Nova Scotia / Nouvelle-Écosse,768060,717140,44660,28690,7485,8485

In [77]:
# Removing the first row from the dataset since we have that as our columns

immigration_data = immigration_data.iloc[1:]
immigration_data.head()

,Immigrant status and period of immigration,Total - Immigrant status and period of immigration,Non-immigrants,Immigrants,Before 1996,1996 to 2005,2006 to 2011
1,Canada,27259525,20543700,6398855,3837770,1620885,940195
2,Newfoundland and Labrador,431045,421170,8315,5415,1215,1690
3,Prince Edward Island,114195,107085,6415,3455,920,2035
4,Nova Scotia / Nouvelle-Écosse,768060,717140,44660,28690,7485,8485
5,New Brunswick / Nouveau-Brunswick,622440,593840,25890,16530,3970,5395

In [78]:
# We will now change the names of our columns that are more readable and understandable

immigration_data = immigration_data.rename(columns = {'Immigrant status and period of immigration' : 'GEO', 'Total - Immigrant status and period of immigration': 'Total'})
immigration_data.head()

,GEO,Total,Non-immigrants,Immigrants,Before 1996,1996 to 2005,2006 to 2011
1,Canada,27259525,20543700,6398855,3837770,1620885,940195
2,Newfoundland and Labrador,431045,421170,8315,5415,1215,1690
3,Prince Edward Island,114195,107085,6415,3455,920,2035
4,Nova Scotia / Nouvelle-Écosse,768060,717140,44660,28690,7485,8485
5,New Brunswick / Nouveau-Brunswick,622440,593840,25890,16530,3970,5395

In [79]:
# checking the columns of the immigration dataset

immigration_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 1 to 25
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GEO               25 non-null     object
 1   Total             25 non-null     object
 2     Non-immigrants  25 non-null     object
 3     Immigrants      25 non-null     object
 4       Before 1996   25 non-null     object
 5       1996 to 2005  25 non-null     object
 6       2006 to 2011  25 non-null     object
dtypes: object(7)
memory usage: 1.5+ KB

### Both of the datasets (housing_date & immigration_data) are in correct format

**Lets look at the columns of the datasets**

In [80]:
# columns of the housing_data

housing_data.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'New housing price indexes', 'UOM',
       'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE',
       'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='object')

In [81]:
# columns of the immigration_data

immigration_data.columns

Index(['GEO', 'Total', '  Non-immigrants', '  Immigrants', '    Before 1996',
       '    1996 to 2005', '    2006 to 2011'],
      dtype='object', name=0)

In [82]:
# immigration_date has some issues
# Notice there are leading and trailing white spaces in the names of our columns which will make it difficult to access them
# Removing the leading and trailing white spaces

immigration_data.columns = immigration_data.columns.str.strip()
immigration_data.columns

Index(['GEO', 'Total', 'Non-immigrants', 'Immigrants', 'Before 1996',
       '1996 to 2005', '2006 to 2011'],
      dtype='object', name=0)

In [83]:

immigration_data['Total'] = pd.to_numeric(immigration_data['Total'])
immigration_data['Non-immigrants'] = pd.to_numeric(immigration_data['Non-immigrants'])
immigration_data['Immigrants'] = pd.to_numeric(immigration_data['Immigrants'])
immigration_data['Before 1996'] = pd.to_numeric(immigration_data['Before 1996'])
immigration_data['1996 to 2005'] = pd.to_numeric(immigration_data['1996 to 2005'])
immigration_data['2006 to 2011'] = pd.to_numeric(immigration_data['2006 to 2011'])

immigration_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 1 to 25
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GEO             25 non-null     object
 1   Total           25 non-null     int64
 2   Non-immigrants  25 non-null     int64
 3   Immigrants      25 non-null     int64
 4   Before 1996     25 non-null     int64
 5   1996 to 2005    25 non-null     int64
 6   2006 to 2011    25 non-null     int64
dtypes: int64(6), object(1)
memory usage: 1.5+ KB

In [84]:
immigration_data.head()

,GEO,Total,Non-immigrants,Immigrants,Before 1996,1996 to 2005,2006 to 2011
1,Canada,27259525,20543700,6398855,3837770,1620885,940195
2,Newfoundland and Labrador,431045,421170,8315,5415,1215,1690
3,Prince Edward Island,114195,107085,6415,3455,920,2035
4,Nova Scotia / Nouvelle-Écosse,768060,717140,44660,28690,7485,8485
5,New Brunswick / Nouveau-Brunswick,622440,593840,25890,16530,3970,5395

In [85]:
# Our dates are in wide format and needs to be changed into long format
# We will add a single column for the dates and their corresponding value will be in a new column i.e. "New Immigrants"

immigration_data = pd.melt(immigration_data, id_vars= ['GEO', 'Total','Non-immigrants','Immigrants'], value_vars = ['Before 1996', '1996 to 2005', '2006 to 2011'], var_name= 'Date', 
             value_name='New Immigrants')

In [104]:
immigration_data.head(60)

,GEO,Total,Non-immigrants,Immigrants,Date,New Immigrants
0,Canada,27259525,20543700,6398855,Before 1996,3837770
1,Newfoundland and Labrador,431045,421170,8315,Before 1996,5415
2,Prince Edward Island,114195,107085,6415,Before 1996,3455
3,Nova Scotia,768060,717140,44660,Before 1996,28690
4,New Brunswick,622440,593840,25890,Before 1996,16530
5,Quebec,6474590,5511745,902990,Before 1996,496790
6,Ontario,10473665,6912395,3442895,Before 1996,2148600
7,Manitoba,946940,774365,165005,Before 1996,90000
8,Saskatchewan,812505,744685,60500,Before 1996,29120
9,Alberta,2888740,2239430,596100,Before 1996,322145
10,British Columbia,3646840,2448855,1139255,Before 1996,693115
11,Yukon,27495,23630,3550,Before 1996,2220
12,Northwest Territories,31755,28740,2695,Before 1996,1355
13,Nunavut,21255,20625,575,Before 1996,330
14,St. John's CMA,162995,156385,5325,Before 1996,3245
15,Halifax CMA,325050,292010,28685,Before 1996,16775
16,Québec City CMA,634200,602990,28605,Before 1996,11985
17,Montréal CMA,3120060,2278110,789440,Before 1996,439575
18,Ottawa - Gatineau CMA,1005005,773525,220640,Before 1996,130700
19,Toronto CMA,4546140,2047970,2416425,Before 1996,1408665
20,Winnipeg CMA,590295,451125,133380,Before 1996,74005
21,Regina CMA,170070,149025,19055,Before 1996,9415
22,Calgary CMA,976570,665410,290760,Before 1996,145920
23,Edmonton CMA,935285,698240,216460,Before 1996,123735
24,Vancouver CMA,1926230,1009070,870035,Before 1996,486590
25,Canada,27259525,20543700,6398855,1996 to 2005,1620885
26,Newfoundland and Labrador,431045,421170,8315,1996 to 2005,1215
27,Prince Edward Island,114195,107085,6415,1996 to 2005,920
28,Nova Scotia,768060,717140,44660,1996 to 2005,7485
29,New Brunswick,622440,593840,25890,1996 to 2005,3970
30,Quebec,6474590,5511745,902990,1996 to 2005,227160
31,Ontario,10473665,6912395,3442895,1996 to 2005,884025
32,Manitoba,946940,774365,165005,1996 to 2005,31800
33,Saskatchewan,812505,744685,60500,1996 to 2005,11165
34,Alberta,2888740,2239430,596100,1996 to 2005,159920
35,British Columbia,3646840,2448855,1139255,1996 to 2005,291810
36,Yukon,27495,23630,3550,1996 to 2005,580
37,Northwest Territories,31755,28740,2695,1996 to 2005,695
38,Nunavut,21255,20625,575,1996 to 2005,145
39,St. John's CMA,162995,156385,5325,1996 to 2005,820
40,Halifax CMA,325050,292010,28685,1996 to 2005,5380
41,Québec City CMA,634200,602990,28605,1996 to 2005,8515
42,Montréal CMA,3120060,2278110,789440,1996 to 2005,196205
43,Ottawa - Gatineau CMA,1005005,773525,220640,1996 to 2005,57975
44,Toronto CMA,4546140,2047970,2416425,1996 to 2005,691240
45,Winnipeg CMA,590295,451125,133380,1996 to 2005,24695
46,Regina CMA,170070,149025,19055,1996 to 2005,3690
47,Calgary CMA,976570,665410,290760,1996 to 2005,88405
48,Edmonton CMA,935285,698240,216460,1996 to 2005,52650
49,Vancouver CMA,1926230,1009070,870035,1996 to 2005,253685
50,Canada,27259525,20543700,6398855,2006 to 2011,940195
51,Newfoundland and Labrador,431045,421170,8315,2006 to 2011,1690
52,Prince Edward Island,114195,107085,6415,2006 to 2011,2035
53,Nova Scotia,768060,717140,44660,2006 to 2011,8485
54,New Brunswick,622440,593840,25890,2006 to 2011,5395
55,Quebec,6474590,5511745,902990,2006 to 2011,179040
56,Ontario,10473665,6912395,3442895,2006 to 2011,410270
57,Manitoba,946940,774365,165005,2006 to 2011,43205
58,Saskatchewan,812505,744685,60500,2006 to 2011,20215
59,Alberta,2888740,2239430,596100,2006 to 2011,114030

### Joining both datasets

**In order to join the two datasets we need a similar column/s**

In [87]:
# We need to make the dates similar in both datasets
# Since we have limited information in the immigration dataset, hence we will convert the dates in the housing data

# First we will convert the REF_DATE to datetime type
housing_data['REF_DATE'] = pd.to_datetime(housing_data['REF_DATE'])
housing_data['REF_DATE']

0       1981-01-01
1       1981-01-01
2       1981-01-01
3       1981-01-01
4       1981-01-01
           ...
61915   2023-12-01
61916   2023-12-01
61917   2023-12-01
61918   2023-12-01
61919   2023-12-01
Name: REF_DATE, Length: 61920, dtype: datetime64[ns]

In [88]:
# Now we will change the dates to match the dates in the immigration data
# Any dates that comes before 1996 -> before 1996  
# Any dates between 1996 and 2005 -> 1996 to 2005
# Any dates between 2006 and 2011 -> 2006 to 2011

housing_data['Date'] = 'Before 1996'
housing_data.loc[(housing_data['REF_DATE'] >= '1996-01-01') & (housing_data['REF_DATE'] < '2006-01-01'), 'Date'] = '1996 to 2005'
housing_data.loc[(housing_data['REF_DATE'] >= '2006-01-01') & (housing_data['REF_DATE'] < '2012-01-01'), 'Date'] = '2006 to 2011'
housing_data.loc[(housing_data['REF_DATE'] >= '2012-01-01'), 'Date'] = 'After 2011'

# checking the unique values in the Data column to see if they are same as in the immigration data
# There is one extra value for the Date column i.e."After 2011" 
# This extra value will help us to discard that timeframe since it is not in our immigration data
housing_data['Date'].unique()

array(['Before 1996', '1996 to 2005', '2006 to 2011', 'After 2011'],
      dtype=object)

In [89]:
# Lets remove the columns in the housing data that does not contain any meaningful data for our analysis

housing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61920 entries, 0 to 61919
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   REF_DATE                   61920 non-null  datetime64[ns]
 1   GEO                        61920 non-null  object
 2   DGUID                      60372 non-null  object
 3   New housing price indexes  61920 non-null  object
 4   UOM                        61920 non-null  object
 5   UOM_ID                     61920 non-null  int64
 6   SCALAR_FACTOR              61920 non-null  object
 7   SCALAR_ID                  61920 non-null  int64
 8   VECTOR                     61920 non-null  object
 9   COORDINATE                 61920 non-null  float64
 10  VALUE                      51094 non-null  float64
 11  STATUS                     28132 non-null  object
 12  SYMBOL                     0 non-null      float64
 13  TERMINATED                 0 non-null      float64
 14  DECIMALS                   61920 non-null  int64
 15  Date                       61920 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(3), object(8)
memory usage: 7.6+ MB

In [90]:
# Removing the columns that are not required for our analysis

housing_data.columns = housing_data.columns.str.strip()
col_to_drop = ['REF_DATE', 'SYMBOL', 'TERMINATED', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'DECIMALS']
housing_data.drop(columns = col_to_drop, inplace= True) 
housing_data.head()

,GEO,DGUID,New housing price indexes,UOM,COORDINATE,VALUE,STATUS,Date
0,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,38.2,NaN,Before 1996
1,Canada,2016A000011124,House only,"Index, 201612=100",1.2,36.1,NaN,Before 1996
2,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.6,E,Before 1996
3,Atlantic Region,2016A00011,Total (house and land),"Index, 201612=100",2.1,NaN,..,Before 1996
4,Atlantic Region,2016A00011,House only,"Index, 201612=100",2.2,NaN,..,Before 1996

### Lets clean the columns that we are merging our data on:

In [91]:
# Lets look at the provinces in our immigration dataset

immigration_data['GEO'].unique()

array(['Canada ', '  Newfoundland and Labrador', '  Prince Edward Island',
       '  Nova Scotia / Nouvelle-Écosse',
       '  New Brunswick / Nouveau-Brunswick', '  Quebec', '  Ontario',
       '  Manitoba', '  Saskatchewan', '  Alberta', '  British Columbia',
       '  Yukon', '  Northwest Territories', '  Nunavut',
       "St. John's CMA", 'Halifax CMA', 'Québec City CMA', 'Montréal CMA',
       'Ottawa - Gatineau CMA', 'Toronto CMA', 'Winnipeg CMA',
       'Regina CMA', 'Calgary CMA', 'Edmonton CMA', 'Vancouver CMA'],
      dtype=object)

In [92]:
# Notice there are two provinces that are named in French as well as in English. We need only the Engish names so we can match the columns with other data

# Removing the French names for the provinces

immigration_data['GEO'] = immigration_data['GEO'].str.replace(r'\s*/\s.+', '')
immigration_data['GEO'].unique()

C:\Users\hunai\AppData\Local\Temp\ipykernel_12276\1882520372.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  immigration_data['GEO'] = immigration_data['GEO'].str.replace(r'\s*/\s.+', '')

array(['Canada ', '  Newfoundland and Labrador', '  Prince Edward Island',
       '  Nova Scotia', '  New Brunswick', '  Quebec', '  Ontario',
       '  Manitoba', '  Saskatchewan', '  Alberta', '  British Columbia',
       '  Yukon', '  Northwest Territories', '  Nunavut',
       "St. John's CMA", 'Halifax CMA', 'Québec City CMA', 'Montréal CMA',
       'Ottawa - Gatineau CMA', 'Toronto CMA', 'Winnipeg CMA',
       'Regina CMA', 'Calgary CMA', 'Edmonton CMA', 'Vancouver CMA'],
      dtype=object)

In [93]:
# There are leading and trailing spaces in the provinces; need to clean them up

immigration_data['GEO'] = immigration_data['GEO'].str.strip()
immigration_data['GEO'].unique()

array(['Canada', 'Newfoundland and Labrador', 'Prince Edward Island',
       'Nova Scotia', 'New Brunswick', 'Quebec', 'Ontario', 'Manitoba',
       'Saskatchewan', 'Alberta', 'British Columbia', 'Yukon',
       'Northwest Territories', 'Nunavut', "St. John's CMA",
       'Halifax CMA', 'Québec City CMA', 'Montréal CMA',
       'Ottawa - Gatineau CMA', 'Toronto CMA', 'Winnipeg CMA',
       'Regina CMA', 'Calgary CMA', 'Edmonton CMA', 'Vancouver CMA'],
      dtype=object)

In [94]:
# Lets remove any leading and trailing spaces in merging column in the Housing Dataset as well

housing_data['GEO'] = housing_data['GEO'].str.strip()

In [95]:
# We will perfrom the JOIN and will merge both datasets on the time frame and Area/GEO

# Creating a new dataframe for the join
key_columns = ['GEO', 'Date']
housing_immigration_merged = pd.merge(housing_data, immigration_data, on= key_columns, how='inner')

In [96]:
# Lets check how many Provinces we have in our merged dataset (Canada has 10 provinces)

housing_immigration_merged['GEO'].unique()

array(['Canada', 'Newfoundland and Labrador', 'Prince Edward Island',
       'Nova Scotia', 'New Brunswick', 'Quebec', 'Ontario', 'Manitoba',
       'Saskatchewan', 'Alberta', 'British Columbia'], dtype=object)

In [97]:
# We can see all the 10 provinces are in our combined dataset and as well as an overall value for Canada

# Let's take a look at the rows of our new dataframe
housing_immigration_merged.head()

,GEO,DGUID,New housing price indexes,UOM,COORDINATE,VALUE,STATUS,Date,Total,Non-immigrants,Immigrants,New Immigrants
0,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,38.2,NaN,Before 1996,27259525,20543700,6398855,3837770
1,Canada,2016A000011124,House only,"Index, 201612=100",1.2,36.1,NaN,Before 1996,27259525,20543700,6398855,3837770
2,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.6,E,Before 1996,27259525,20543700,6398855,3837770
3,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,38.7,NaN,Before 1996,27259525,20543700,6398855,3837770
4,Canada,2016A000011124,House only,"Index, 201612=100",1.2,36.5,NaN,Before 1996,27259525,20543700,6398855,3837770

In [99]:
# Swtiching the position of the Data column to be the first column and GEO to be the second column

date_col = housing_immigration_merged.pop('Date')
housing_immigration_merged.insert(0, 'Date', date_col)
housing_immigration_merged.head()

,Date,GEO,DGUID,New housing price indexes,UOM,COORDINATE,VALUE,STATUS,Total,Non-immigrants,Immigrants,New Immigrants
0,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,38.2,NaN,27259525,20543700,6398855,3837770
1,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,36.1,NaN,27259525,20543700,6398855,3837770
2,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.6,E,27259525,20543700,6398855,3837770
3,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,38.7,NaN,27259525,20543700,6398855,3837770
4,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,36.5,NaN,27259525,20543700,6398855,3837770
5,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,41.0,E,27259525,20543700,6398855,3837770
6,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,39.3,NaN,27259525,20543700,6398855,3837770
7,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,37.3,NaN,27259525,20543700,6398855,3837770
8,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,41.1,E,27259525,20543700,6398855,3837770
9,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,39.9,NaN,27259525,20543700,6398855,3837770
10,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.1,NaN,27259525,20543700,6398855,3837770
11,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,41.2,E,27259525,20543700,6398855,3837770
12,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.6,NaN,27259525,20543700,6398855,3837770
13,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.9,NaN,27259525,20543700,6398855,3837770
14,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,41.5,E,27259525,20543700,6398855,3837770
15,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.8,NaN,27259525,20543700,6398855,3837770
16,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,39.1,NaN,27259525,20543700,6398855,3837770
17,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,41.6,E,27259525,20543700,6398855,3837770
18,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.8,NaN,27259525,20543700,6398855,3837770
19,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,39.2,NaN,27259525,20543700,6398855,3837770
20,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,41.6,E,27259525,20543700,6398855,3837770
21,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.6,NaN,27259525,20543700,6398855,3837770
22,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,39.0,NaN,27259525,20543700,6398855,3837770
23,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,41.5,E,27259525,20543700,6398855,3837770
24,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.4,NaN,27259525,20543700,6398855,3837770
25,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,39.0,NaN,27259525,20543700,6398855,3837770
26,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.9,E,27259525,20543700,6398855,3837770
27,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.3,NaN,27259525,20543700,6398855,3837770
28,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.8,NaN,27259525,20543700,6398855,3837770
29,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.9,E,27259525,20543700,6398855,3837770
30,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.2,NaN,27259525,20543700,6398855,3837770
31,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.8,NaN,27259525,20543700,6398855,3837770
32,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.4,E,27259525,20543700,6398855,3837770
33,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.3,NaN,27259525,20543700,6398855,3837770
34,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.9,NaN,27259525,20543700,6398855,3837770
35,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.5,E,27259525,20543700,6398855,3837770
36,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.3,NaN,27259525,20543700,6398855,3837770
37,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,39.1,NaN,27259525,20543700,6398855,3837770
38,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.5,E,27259525,20543700,6398855,3837770
39,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.3,NaN,27259525,20543700,6398855,3837770
40,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.9,NaN,27259525,20543700,6398855,3837770
41,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.6,E,27259525,20543700,6398855,3837770
42,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,40.1,NaN,27259525,20543700,6398855,3837770
43,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.6,NaN,27259525,20543700,6398855,3837770
44,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.7,E,27259525,20543700,6398855,3837770
45,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,39.9,NaN,27259525,20543700,6398855,3837770
46,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.5,NaN,27259525,20543700,6398855,3837770
47,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.6,E,27259525,20543700,6398855,3837770
48,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,39.6,NaN,27259525,20543700,6398855,3837770
49,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.1,NaN,27259525,20543700,6398855,3837770
50,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,40.1,E,27259525,20543700,6398855,3837770
51,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,39.3,NaN,27259525,20543700,6398855,3837770
52,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.1,NaN,27259525,20543700,6398855,3837770
53,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,39.5,E,27259525,20543700,6398855,3837770
54,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,39.0,NaN,27259525,20543700,6398855,3837770
55,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,38.0,NaN,27259525,20543700,6398855,3837770
56,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,38.5,E,27259525,20543700,6398855,3837770
57,Before 1996,Canada,2016A000011124,Total (house and land),"Index, 201612=100",1.1,38.8,NaN,27259525,20543700,6398855,3837770
58,Before 1996,Canada,2016A000011124,House only,"Index, 201612=100",1.2,37.8,NaN,27259525,20543700,6398855,3837770
59,Before 1996,Canada,2016A000011124,Land only,"Index, 201612=100",1.3,38.2,E,27259525,20543700,6398855,3837770

### ******************************************************************************************